#!/usr/bin/env node

/**
 * Post-install script to generate Prisma Client and create index.ts
 * This ensures @/generated/prisma imports work correctly with Next.js/Turbopack
 * 
 * IMPORTANT: This script only generates Prisma Client. It does NOT:
 * - Execute migrations (prisma migrate)
 * - Access the database
 * - Read or write clinical data
 * 
 * According to spec: docs/24_build_vercel_specs.md
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Generate Prisma Client
console.log('Generating Prisma Client...');
try {
  execSync('npx prisma generate', { 
    stdio: 'inherit',
    env: { ...process.env }
  });
  console.log('✓ Prisma Client generated successfully');
} catch (error) {
  console.error('✗ ERROR: Failed to generate Prisma Client');
  console.error('✗ This build will fail. Prisma Client is required for the application to compile.');
  console.error('✗ Error details:', error.message);
  process.exit(1);
}

// Verify Prisma Client was generated
const prismaOutputDir = path.join(__dirname, '..', 'src', 'generated', 'prisma');
if (!fs.existsSync(prismaOutputDir)) {
  console.error('✗ ERROR: Prisma Client output directory does not exist after generation');
  console.error(`✗ Expected directory: ${prismaOutputDir}`);
  process.exit(1);
}

// Create index.ts file to re-export everything
const indexFilePath = path.join(prismaOutputDir, 'index.ts');

try {
  const indexContent = `// Re-export everything from client.ts to make @/generated/prisma imports work
// This file is auto-generated by scripts/postinstall-prisma.js
export * from './client';
export * from './enums';
export * from './models';
`;

  fs.writeFileSync(indexFilePath, indexContent, 'utf8');
  console.log('✓ Created index.ts for Prisma Client exports');
} catch (error) {
  console.error('✗ ERROR: Failed to create index.ts file');
  console.error('✗ Error details:', error.message);
  process.exit(1);
}

console.log('✓ Post-install script completed successfully');
