#!/usr/bin/env node

/**
 * Post-install script to generate Prisma Client and create index.ts
 * This ensures @/generated/prisma imports work correctly with Next.js/Turbopack
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Generate Prisma Client
console.log('Generating Prisma Client...');
execSync('npx prisma generate', { stdio: 'inherit' });

// Create index.ts file to re-export everything
const prismaOutputDir = path.join(__dirname, '..', 'src', 'generated', 'prisma');
const indexFilePath = path.join(prismaOutputDir, 'index.ts');

const indexContent = `// Re-export everything from client.ts to make @/generated/prisma imports work
// This file is auto-generated by scripts/postinstall-prisma.js
export * from './client';
export * from './enums';
export * from './models';
`;

fs.writeFileSync(indexFilePath, indexContent, 'utf8');
console.log('Created index.ts for Prisma Client exports');
